// SPDX-License-Identifier: MIT

/* AUTOGENERATED FILE BY HARDHAT-ZKIT. DO NOT EDIT. */

pragma solidity >=0.7.0 <0.9.0;

contract BurnCircuitGroth16Verifier {
    // @dev scalar field size
    uint256 public constant SCALAR_FIELD_SIZE =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;
    /// @dev base field size
    uint256 public constant BASE_FIELD_SIZE =
        21888242871839275222246405745257275088696311157297823662689037894645226208583;

    /// @dev verification key data
    uint256 public constant ALPHA_X =
        20491192805390485299153009773594534940189261866228447918068658471970481763042;
    uint256 public constant ALPHA_Y =
        9383485363053290200918347156157836566562967994039712273449902621266178545958;
    uint256 public constant BETA_X1 =
        4252822878758300859123897981450591353533073413197771768651442665752259397132;
    uint256 public constant BETA_X2 =
        6375614351688725206403948262868962793625744043794305715222011528459656738731;
    uint256 public constant BETA_Y1 =
        21847035105528745403288232691147584728191162732299865338377159692350059136679;
    uint256 public constant BETA_Y2 =
        10505242626370262277552901082094356697409835680220590971873171140371331206856;
    uint256 public constant GAMMA_X1 =
        11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 public constant GAMMA_X2 =
        10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 public constant GAMMA_Y1 =
        4082367875863433681332203403145435568316851327593401208105741076214120093531;
    uint256 public constant GAMMA_Y2 =
        8495653923123431417604973247489272438418190587263600148770280649306958101930;
    uint256 public constant DELTA_X1 =
        18068269036347605663473046598932117849250599112501411921245619099639563001463;
    uint256 public constant DELTA_X2 =
        2301073142475396993773978505633718782750287996612198183593216235602225785330;
    uint256 public constant DELTA_Y1 =
        3073145107905170746687841711267307719073762517109452847153814168939630075772;
    uint256 public constant DELTA_Y2 =
        10961296788526809772353740184537068352606427639693845063421291358100730194549;

    uint256 public constant IC0_X =
        14874534560863506187492139018634993019793584672384344989283815636520951511298;
    uint256 public constant IC0_Y =
        19433767728097878428205026753935379413283455462187619513628741184855994988529;
    uint256 public constant IC1_X =
        766312427469543414624781412742178740436577019446000599209144238628925292414;
    uint256 public constant IC1_Y =
        11956596380120466965959213032841211036588141256244479446912141909087743946449;
    uint256 public constant IC2_X =
        19382367631125777024854089319372587940591402333899244040325149591553843397579;
    uint256 public constant IC2_Y =
        21403189616005894915395729633979911132499330629008284763677855495728980685589;
    uint256 public constant IC3_X =
        16873607939260699782152987377956714326707996147740333372471409440806666007870;
    uint256 public constant IC3_Y =
        4823813718136831027557208358400077597181121551803781304866108582065943338847;
    uint256 public constant IC4_X =
        1929042304597372185937147232117975513235946186018483019137219886969879342564;
    uint256 public constant IC4_Y =
        16041200717617907290182387211838729202813038927716409271158182722220738184272;
    uint256 public constant IC5_X =
        10100132593539651075092860762732050318282008836770498758516080145892203319933;
    uint256 public constant IC5_Y =
        20955597788595471241113414219690472105385243566077669548840483820580533529000;
    uint256 public constant IC6_X =
        8470926007784285402889150113766497592074358400891318532322995138506403384279;
    uint256 public constant IC6_Y =
        8310950274532158280101970082879701558099714295351544024093409514778108626712;
    uint256 public constant IC7_X =
        19978173907576057065444722831289895208882188362747184086352903798679295119201;
    uint256 public constant IC7_Y =
        15183736862969267858591121906253501216802708436126732016994140949207117595013;
    uint256 public constant IC8_X =
        4241991590840894812521558873691922742505044386758211905612996694701369418750;
    uint256 public constant IC8_Y =
        4712959178917328940867212891418986989954694508210057281434702756286365863599;
    uint256 public constant IC9_X =
        17384256984235466163214682780551664577091564886844441439437963151187110314064;
    uint256 public constant IC9_Y =
        20296571661331082956968105383442818985984992535310861363986529155505576301282;
    uint256 public constant IC10_X =
        17027431616611009304378410217174272480143349850791163137585063755548142788022;
    uint256 public constant IC10_Y =
        20118286149998664902129684191444860379452289136986877466159896830141693633470;
    uint256 public constant IC11_X =
        20835339050759225768703712848075529739635791514709813530848117559567280414938;
    uint256 public constant IC11_Y =
        7040368151836048017923729126580755497072054472683430007432499359028824547816;
    uint256 public constant IC12_X =
        20062320405151278545619584038566861254083477237663892701639147906154006315477;
    uint256 public constant IC12_Y =
        17523041307652932190125641730118738313390334657045299125403856004388564657068;
    uint256 public constant IC13_X =
        13052049171820219952433931907681657393694797308477474074698115842501295147916;
    uint256 public constant IC13_Y =
        1425640142139256702451940144848264084151874944916879752002334659577479016496;
    uint256 public constant IC14_X =
        4181557413177047880795852900430710069406648434565017206282272466766706932824;
    uint256 public constant IC14_Y =
        1076490384996164187408939956231269371661746698521764954497727070931306852324;
    uint256 public constant IC15_X =
        10477370403873963103009023823231137877228587266934872051738072656898318034377;
    uint256 public constant IC15_Y =
        11502980528392834515632224102695746324276378296202650174921624745967235773112;
    uint256 public constant IC16_X =
        7349403818132382069242774903158300506281160147593600216352343709478834507839;
    uint256 public constant IC16_Y =
        5374170652494686658605512370545122605691962258852673576709426080364171645245;
    uint256 public constant IC17_X =
        8971493727614399525916816483074861570535678898719425110239304688703813492918;
    uint256 public constant IC17_Y =
        11607506224512849900066565004118629841042445789946723208255902316075236531264;
    uint256 public constant IC18_X =
        11633076084066714087007356724903241887267836906856444905783519811005119761103;
    uint256 public constant IC18_Y =
        15434440522489358811942244383448136662781089528873872838765763684395176114351;
    uint256 public constant IC19_X =
        14649394179930981032894187227537055207828915729716249122436764256795900134741;
    uint256 public constant IC19_Y =
        14359000287667049950671539992097470155808991877715693905424132958170028923673;
    
    /// @dev memory pointer sizes
    uint16 public constant P_PUBLIC_SIGNALS_ACCUMULATOR_SIZE = 128;
    uint16 public constant P_TOTAL_SIZE = 896;

    function verifyProof(
        uint256[2] memory pointA_,
        uint256[2][2] memory pointB_,
        uint256[2] memory pointC_,
        uint256[19] memory publicSignals_
    ) public view returns (bool verified_) {
        assembly {
            function checkField(signal_) -> res_ {
                res_ := lt(signal_, SCALAR_FIELD_SIZE)
            }

            function g1MulAdd(pR_, x_, y_, s_) -> res_ {
                let pointer_ := mload(64) // free pointer

                mstore(pointer_, x_)
                mstore(add(pointer_, 32), y_)
                mstore(add(pointer_, 64), s_)

                res_ := staticcall(6000, 7, pointer_, 96, pointer_, 64) // ecMul
                res_ := and(res_, gt(returndatasize(), 0)) // check that multiplication succeeded

                if iszero(res_) {
                    leave
                }

                mstore(add(pointer_, 64), mload(pR_))
                mstore(add(pointer_, 96), mload(add(pR_, 32)))

                res_ := staticcall(150, 6, pointer_, 128, pR_, 64) // ecAdd
                res_ := and(res_, gt(returndatasize(), 0)) // check that addition succeeded
            }

            function checkPairing(pA_, pB_, pC_, pubSignals_, pointer_) -> res_ {
                let pPairing_ := add(pointer_, P_PUBLIC_SIGNALS_ACCUMULATOR_SIZE)

                mstore(pointer_, IC0_X)
                mstore(add(pointer_, 32), IC0_Y)

                /// @dev compute the linear combination of public signals
                if iszero(g1MulAdd(pointer_, IC1_X, IC1_Y, mload(add(pubSignals_, 0)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC2_X, IC2_Y, mload(add(pubSignals_, 32)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC3_X, IC3_Y, mload(add(pubSignals_, 64)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC4_X, IC4_Y, mload(add(pubSignals_, 96)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC5_X, IC5_Y, mload(add(pubSignals_, 128)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC6_X, IC6_Y, mload(add(pubSignals_, 160)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC7_X, IC7_Y, mload(add(pubSignals_, 192)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC8_X, IC8_Y, mload(add(pubSignals_, 224)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC9_X, IC9_Y, mload(add(pubSignals_, 256)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC10_X, IC10_Y, mload(add(pubSignals_, 288)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC11_X, IC11_Y, mload(add(pubSignals_, 320)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC12_X, IC12_Y, mload(add(pubSignals_, 352)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC13_X, IC13_Y, mload(add(pubSignals_, 384)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC14_X, IC14_Y, mload(add(pubSignals_, 416)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC15_X, IC15_Y, mload(add(pubSignals_, 448)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC16_X, IC16_Y, mload(add(pubSignals_, 480)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC17_X, IC17_Y, mload(add(pubSignals_, 512)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC18_X, IC18_Y, mload(add(pubSignals_, 544)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC19_X, IC19_Y, mload(add(pubSignals_, 576)))) {
                    leave
                }
                
                /// @dev -A
                mstore(pPairing_, mload(pA_))
                mstore(
                    add(pPairing_, 32),
                    mod(sub(BASE_FIELD_SIZE, mload(add(pA_, 32))), BASE_FIELD_SIZE)
                )

                /// @dev B
                mstore(add(pPairing_, 64), mload(mload(pB_)))
                mstore(add(pPairing_, 96), mload(add(mload(pB_), 32)))
                mstore(add(pPairing_, 128), mload(mload(add(pB_, 32))))
                mstore(add(pPairing_, 160), mload(add(mload(add(pB_, 32)), 32)))

                /// @dev alpha1
                mstore(add(pPairing_, 192), ALPHA_X)
                mstore(add(pPairing_, 224), ALPHA_Y)

                /// @dev beta2
                mstore(add(pPairing_, 256), BETA_X1)
                mstore(add(pPairing_, 288), BETA_X2)
                mstore(add(pPairing_, 320), BETA_Y1)
                mstore(add(pPairing_, 352), BETA_Y2)

                /// @dev public signals
                mstore(add(pPairing_, 384), mload(pointer_))
                mstore(add(pPairing_, 416), mload(add(pointer_, 32)))

                /// @dev gamma2
                mstore(add(pPairing_, 448), GAMMA_X1)
                mstore(add(pPairing_, 480), GAMMA_X2)
                mstore(add(pPairing_, 512), GAMMA_Y1)
                mstore(add(pPairing_, 544), GAMMA_Y2)

                /// @dev C
                mstore(add(pPairing_, 576), mload(pC_))
                mstore(add(pPairing_, 608), mload(add(pC_, 32)))

                /// @dev delta2
                mstore(add(pPairing_, 640), DELTA_X1)
                mstore(add(pPairing_, 672), DELTA_X2)
                mstore(add(pPairing_, 704), DELTA_Y1)
                mstore(add(pPairing_, 736), DELTA_Y2)

                res_ := staticcall(181000, 8, pPairing_, 768, pPairing_, 32) // ecPairing
                res_ := and(res_, mload(pPairing_)) // check that pairing succeeded
            }

            let pointer_ := mload(64) // free pointer
            mstore(64, add(pointer_, P_TOTAL_SIZE))

            /// @dev check that all public signals are in F
            verified_ := 1
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 0))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 32))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 64))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 96))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 128))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 160))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 192))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 224))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 256))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 288))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 320))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 352))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 384))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 416))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 448))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 480))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 512))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 544))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 576))))
            
            /// @dev check pairings
            if not(iszero(verified_)) {
                verified_ := checkPairing(pointA_, pointB_, pointC_, publicSignals_, pointer_)
            }
        }
    }
}
