// SPDX-License-Identifier: MIT

/* AUTOGENERATED FILE BY HARDHAT-ZKIT. DO NOT EDIT. */

pragma solidity >=0.7.0 <0.9.0;

contract MintCircuitGroth16Verifier {
    // @dev scalar field size
    uint256 public constant SCALAR_FIELD_SIZE =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;
    /// @dev base field size
    uint256 public constant BASE_FIELD_SIZE =
        21888242871839275222246405745257275088696311157297823662689037894645226208583;

    /// @dev verification key data
    uint256 public constant ALPHA_X =
        20491192805390485299153009773594534940189261866228447918068658471970481763042;
    uint256 public constant ALPHA_Y =
        9383485363053290200918347156157836566562967994039712273449902621266178545958;
    uint256 public constant BETA_X1 =
        4252822878758300859123897981450591353533073413197771768651442665752259397132;
    uint256 public constant BETA_X2 =
        6375614351688725206403948262868962793625744043794305715222011528459656738731;
    uint256 public constant BETA_Y1 =
        21847035105528745403288232691147584728191162732299865338377159692350059136679;
    uint256 public constant BETA_Y2 =
        10505242626370262277552901082094356697409835680220590971873171140371331206856;
    uint256 public constant GAMMA_X1 =
        11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 public constant GAMMA_X2 =
        10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 public constant GAMMA_Y1 =
        4082367875863433681332203403145435568316851327593401208105741076214120093531;
    uint256 public constant GAMMA_Y2 =
        8495653923123431417604973247489272438418190587263600148770280649306958101930;
    uint256 public constant DELTA_X1 =
        18310150044426911246155186910490046153313456452399821848345822479171865644945;
    uint256 public constant DELTA_X2 =
        5264749735931748850388186461242850611426001497774606367467905923816395425584;
    uint256 public constant DELTA_Y1 =
        14605690245348196568105292901835213150229505840089104796535493429006577126729;
    uint256 public constant DELTA_Y2 =
        6630427478337662007171878244275165608118871321429624618994700701405970952688;

    uint256 public constant IC0_X =
        20861492296691856165309547776629146952527944203201524873006782894760706976421;
    uint256 public constant IC0_Y =
        3358824539307473736604976612722723713450165337804134402240835675528178962335;
    uint256 public constant IC1_X =
        5511753296331491509569296110445894989507167702892869680373063711781065132586;
    uint256 public constant IC1_Y =
        13287934466428012933987353229261913144286871473679533187235673876285899045743;
    uint256 public constant IC2_X =
        19440605787728638102373686494108905895654642611628169437813543523912920918974;
    uint256 public constant IC2_Y =
        14274851756231214444056769636488865604307347698663402267645432934893285974382;
    uint256 public constant IC3_X =
        15096206644290302729673494593775111017994893610444238941512555843761977798983;
    uint256 public constant IC3_Y =
        10592933405320090517798391416276382767273192109395080940602914940118569597175;
    uint256 public constant IC4_X =
        11189740705109916645368104876865492850094752501799788866350480656624008137866;
    uint256 public constant IC4_Y =
        6373283667837734104667322526110821843542106635322725504401355277194447781077;
    uint256 public constant IC5_X =
        12519464150710176464255689182191223185996416021638864414936748671904429695824;
    uint256 public constant IC5_Y =
        2150352325795278553853916266025032932948033124823106315746500341814425169422;
    uint256 public constant IC6_X =
        15670400985668054227710197257556796204699390148155253521504180141434411169010;
    uint256 public constant IC6_Y =
        8015372489282794800866289250911385611602689183902606383808208685650011045563;
    uint256 public constant IC7_X =
        12391374210603786527505301556990321980257270091806041113978279818540065899945;
    uint256 public constant IC7_Y =
        8515915070842771734194345922664587925823550006589425467896744043022744763705;
    uint256 public constant IC8_X =
        13807538579064566476415694067988365108026713189554400912099239363422127740084;
    uint256 public constant IC8_Y =
        20995630364107562144456318907019459226461425603435703531146140720469843551846;
    uint256 public constant IC9_X =
        16081085598581166173056602246854317663562052634922574354324946451000607120736;
    uint256 public constant IC9_Y =
        4806824913347623486886828480516106843275460973906843187481538273603254862860;
    uint256 public constant IC10_X =
        11631320333320389002311111478825925862454422531020071627586226192130355210011;
    uint256 public constant IC10_Y =
        2122514671452018862991564551128667346496598894933582018300009947844480163204;
    uint256 public constant IC11_X =
        15815064186883060030591419160901286559864343154013673260150235611788231912868;
    uint256 public constant IC11_Y =
        20370993525566739028237212283048185476369537192297038935645044346593403445660;
    uint256 public constant IC12_X =
        6595190593163887992768043198968800372382627330961015186275030802761168515160;
    uint256 public constant IC12_Y =
        2507789053059248650011919918385719955910150531313679742117670915630070953153;
    uint256 public constant IC13_X =
        4769024494559532962607971843474329930995364751968913219837397535853989902361;
    uint256 public constant IC13_Y =
        19797571185823382274710714732907626050151097014530262793833343110696004901030;
    uint256 public constant IC14_X =
        3741095076389852568348466376789570229681540891762671038336587701809594295528;
    uint256 public constant IC14_Y =
        21880696756868695397495499774269592625633170331780293853746719644130396141624;
    uint256 public constant IC15_X =
        19517234766997622544803863027312351274688065611950961197914008880953737422764;
    uint256 public constant IC15_Y =
        12766977633088554535159910591318146119749041565098004885165775551772871421614;
    uint256 public constant IC16_X =
        10127707076448967603220797369646569980071434903529645864304691091289486555787;
    uint256 public constant IC16_Y =
        8950621622365938933033410282918462563356088154788396334376499614106955989143;
    uint256 public constant IC17_X =
        320788284794753344254157752272658952160576068967386302073453451172649214954;
    uint256 public constant IC17_Y =
        12072329550178607667412696356075787995621403634036884084426834721001660976904;
    uint256 public constant IC18_X =
        9716709810086398193300932341527162316204048472244916702006365450976523531860;
    uint256 public constant IC18_Y =
        18512681717254787569432573766259952720830104316573624498577507861680140169670;
    uint256 public constant IC19_X =
        15583210451318479388973607383966221956407458266371632140871864321825927352219;
    uint256 public constant IC19_Y =
        7052911310999904477056051359102541062683487166996917722730719394904318138991;
    uint256 public constant IC20_X =
        14254488977079195307288668274622096883962637439954171948445632822972231171922;
    uint256 public constant IC20_Y =
        16635798420556842961701542474296813958571732882037007055705935524616967766953;
    uint256 public constant IC21_X =
        15442808645804769798081357271547630043038154266326625746271433261881929480822;
    uint256 public constant IC21_Y =
        15692133379817904664248323757151648294530592660167042783943929714054883152410;
    uint256 public constant IC22_X =
        3959038117463195264225173297414802417787229629774522795646934460427059533984;
    uint256 public constant IC22_Y =
        18559902898279327965625446054916413498906915191943220953721617187208287362108;
    uint256 public constant IC23_X =
        13117164475757255667489585615497830505771053345067993075233739336894728532922;
    uint256 public constant IC23_Y =
        7549162224805556704746428222814274942147810722690549422145605522701753608061;
    uint256 public constant IC24_X =
        14334222819352589667606721913122724056272442669634927211261504255948038740273;
    uint256 public constant IC24_Y =
        2481751947144260802788900797067145915535069398032899055229950556775735697875;
    
    /// @dev memory pointer sizes
    uint16 public constant P_PUBLIC_SIGNALS_ACCUMULATOR_SIZE = 128;
    uint16 public constant P_TOTAL_SIZE = 896;

    function verifyProof(
        uint256[2] memory pointA_,
        uint256[2][2] memory pointB_,
        uint256[2] memory pointC_,
        uint256[24] memory publicSignals_
    ) public view returns (bool verified_) {
        assembly {
            function checkField(signal_) -> res_ {
                res_ := lt(signal_, SCALAR_FIELD_SIZE)
            }

            function g1MulAdd(pR_, x_, y_, s_) -> res_ {
                let pointer_ := mload(64) // free pointer

                mstore(pointer_, x_)
                mstore(add(pointer_, 32), y_)
                mstore(add(pointer_, 64), s_)

                res_ := staticcall(6000, 7, pointer_, 96, pointer_, 64) // ecMul
                res_ := and(res_, gt(returndatasize(), 0)) // check that multiplication succeeded

                if iszero(res_) {
                    leave
                }

                mstore(add(pointer_, 64), mload(pR_))
                mstore(add(pointer_, 96), mload(add(pR_, 32)))

                res_ := staticcall(150, 6, pointer_, 128, pR_, 64) // ecAdd
                res_ := and(res_, gt(returndatasize(), 0)) // check that addition succeeded
            }

            function checkPairing(pA_, pB_, pC_, pubSignals_, pointer_) -> res_ {
                let pPairing_ := add(pointer_, P_PUBLIC_SIGNALS_ACCUMULATOR_SIZE)

                mstore(pointer_, IC0_X)
                mstore(add(pointer_, 32), IC0_Y)

                /// @dev compute the linear combination of public signals
                if iszero(g1MulAdd(pointer_, IC1_X, IC1_Y, mload(add(pubSignals_, 0)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC2_X, IC2_Y, mload(add(pubSignals_, 32)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC3_X, IC3_Y, mload(add(pubSignals_, 64)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC4_X, IC4_Y, mload(add(pubSignals_, 96)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC5_X, IC5_Y, mload(add(pubSignals_, 128)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC6_X, IC6_Y, mload(add(pubSignals_, 160)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC7_X, IC7_Y, mload(add(pubSignals_, 192)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC8_X, IC8_Y, mload(add(pubSignals_, 224)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC9_X, IC9_Y, mload(add(pubSignals_, 256)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC10_X, IC10_Y, mload(add(pubSignals_, 288)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC11_X, IC11_Y, mload(add(pubSignals_, 320)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC12_X, IC12_Y, mload(add(pubSignals_, 352)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC13_X, IC13_Y, mload(add(pubSignals_, 384)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC14_X, IC14_Y, mload(add(pubSignals_, 416)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC15_X, IC15_Y, mload(add(pubSignals_, 448)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC16_X, IC16_Y, mload(add(pubSignals_, 480)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC17_X, IC17_Y, mload(add(pubSignals_, 512)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC18_X, IC18_Y, mload(add(pubSignals_, 544)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC19_X, IC19_Y, mload(add(pubSignals_, 576)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC20_X, IC20_Y, mload(add(pubSignals_, 608)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC21_X, IC21_Y, mload(add(pubSignals_, 640)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC22_X, IC22_Y, mload(add(pubSignals_, 672)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC23_X, IC23_Y, mload(add(pubSignals_, 704)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC24_X, IC24_Y, mload(add(pubSignals_, 736)))) {
                    leave
                }
                
                /// @dev -A
                mstore(pPairing_, mload(pA_))
                mstore(
                    add(pPairing_, 32),
                    mod(sub(BASE_FIELD_SIZE, mload(add(pA_, 32))), BASE_FIELD_SIZE)
                )

                /// @dev B
                mstore(add(pPairing_, 64), mload(mload(pB_)))
                mstore(add(pPairing_, 96), mload(add(mload(pB_), 32)))
                mstore(add(pPairing_, 128), mload(mload(add(pB_, 32))))
                mstore(add(pPairing_, 160), mload(add(mload(add(pB_, 32)), 32)))

                /// @dev alpha1
                mstore(add(pPairing_, 192), ALPHA_X)
                mstore(add(pPairing_, 224), ALPHA_Y)

                /// @dev beta2
                mstore(add(pPairing_, 256), BETA_X1)
                mstore(add(pPairing_, 288), BETA_X2)
                mstore(add(pPairing_, 320), BETA_Y1)
                mstore(add(pPairing_, 352), BETA_Y2)

                /// @dev public signals
                mstore(add(pPairing_, 384), mload(pointer_))
                mstore(add(pPairing_, 416), mload(add(pointer_, 32)))

                /// @dev gamma2
                mstore(add(pPairing_, 448), GAMMA_X1)
                mstore(add(pPairing_, 480), GAMMA_X2)
                mstore(add(pPairing_, 512), GAMMA_Y1)
                mstore(add(pPairing_, 544), GAMMA_Y2)

                /// @dev C
                mstore(add(pPairing_, 576), mload(pC_))
                mstore(add(pPairing_, 608), mload(add(pC_, 32)))

                /// @dev delta2
                mstore(add(pPairing_, 640), DELTA_X1)
                mstore(add(pPairing_, 672), DELTA_X2)
                mstore(add(pPairing_, 704), DELTA_Y1)
                mstore(add(pPairing_, 736), DELTA_Y2)

                res_ := staticcall(181000, 8, pPairing_, 768, pPairing_, 32) // ecPairing
                res_ := and(res_, mload(pPairing_)) // check that pairing succeeded
            }

            let pointer_ := mload(64) // free pointer
            mstore(64, add(pointer_, P_TOTAL_SIZE))

            /// @dev check that all public signals are in F
            verified_ := 1
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 0))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 32))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 64))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 96))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 128))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 160))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 192))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 224))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 256))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 288))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 320))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 352))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 384))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 416))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 448))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 480))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 512))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 544))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 576))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 608))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 640))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 672))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 704))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 736))))
            
            /// @dev check pairings
            if not(iszero(verified_)) {
                verified_ := checkPairing(pointA_, pointB_, pointC_, publicSignals_, pointer_)
            }
        }
    }
}
