// SPDX-License-Identifier: MIT

/* AUTOGENERATED FILE BY HARDHAT-ZKIT. DO NOT EDIT. */

pragma solidity >=0.7.0 <0.9.0;

contract TransferCircuitGroth16Verifier {
    // @dev scalar field size
    uint256 public constant SCALAR_FIELD_SIZE =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;
    /// @dev base field size
    uint256 public constant BASE_FIELD_SIZE =
        21888242871839275222246405745257275088696311157297823662689037894645226208583;

    /// @dev verification key data
    uint256 public constant ALPHA_X =
        20491192805390485299153009773594534940189261866228447918068658471970481763042;
    uint256 public constant ALPHA_Y =
        9383485363053290200918347156157836566562967994039712273449902621266178545958;
    uint256 public constant BETA_X1 =
        4252822878758300859123897981450591353533073413197771768651442665752259397132;
    uint256 public constant BETA_X2 =
        6375614351688725206403948262868962793625744043794305715222011528459656738731;
    uint256 public constant BETA_Y1 =
        21847035105528745403288232691147584728191162732299865338377159692350059136679;
    uint256 public constant BETA_Y2 =
        10505242626370262277552901082094356697409835680220590971873171140371331206856;
    uint256 public constant GAMMA_X1 =
        11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 public constant GAMMA_X2 =
        10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 public constant GAMMA_Y1 =
        4082367875863433681332203403145435568316851327593401208105741076214120093531;
    uint256 public constant GAMMA_Y2 =
        8495653923123431417604973247489272438418190587263600148770280649306958101930;
    uint256 public constant DELTA_X1 =
        7373421924848631289729447888934244711954095305224812054165477109239634485930;
    uint256 public constant DELTA_X2 =
        17573321420925543398098938841372725442795740456981756646006455900667019185665;
    uint256 public constant DELTA_Y1 =
        6692063395579459319241310567160387612371059945372121369244265991917716889279;
    uint256 public constant DELTA_Y2 =
        14769154824729601962487485960591065507136111829346285041829452037354398605022;

    uint256 public constant IC0_X =
        12860613047485174337572800144367534566676749966427263510786233641288361323072;
    uint256 public constant IC0_Y =
        3117092304906614020388401274042152195443668310800814064571900198159814372456;
    uint256 public constant IC1_X =
        3987203900176313648721373326838294062064875524041579268053604363771992813663;
    uint256 public constant IC1_Y =
        2540870705672409242382324915793065925212335203467790590740070818381371996118;
    uint256 public constant IC2_X =
        2160351009242570345101990598387012245257165805803521679126798467310545830036;
    uint256 public constant IC2_Y =
        2050456376645372578396035075358789073979003008436938146845128992698746141877;
    uint256 public constant IC3_X =
        9819249055709022471783469269872195968940696597382036472257350992099603166183;
    uint256 public constant IC3_Y =
        2401786491025438669071658710401341692741617050151593778325339189669301220899;
    uint256 public constant IC4_X =
        7422007307044478259226064473692631752662233050292352222869411054288745570789;
    uint256 public constant IC4_Y =
        10017850150189997840383565765235365224515214690165127564532641750692280241903;
    uint256 public constant IC5_X =
        19221738488703246937975790853705478702845308522128613703152831351556301989763;
    uint256 public constant IC5_Y =
        10183107801189396942167758711051912294619018039092495644809682417460643023810;
    uint256 public constant IC6_X =
        9076649205859590603560715606056701346727113477211950055621087628388769368386;
    uint256 public constant IC6_Y =
        52455929519905290524842189199006340052096446699011578823444788358568039702;
    uint256 public constant IC7_X =
        18103653070682127942942702359086473888645990538117645003998683697246715437040;
    uint256 public constant IC7_Y =
        20937350421085763292785746194370377209032774713987029070743280053317168289872;
    uint256 public constant IC8_X =
        9758634944624942528872916404218984802068150789828935243358049923155742940304;
    uint256 public constant IC8_Y =
        5615975277864739173632599296778201253863610964605697390030280177993730165032;
    uint256 public constant IC9_X =
        10670001473472856457996828759289176589182316531259991403627649917035565048429;
    uint256 public constant IC9_Y =
        16737644016567474899525575815101539395782539042839027261623709392334896614435;
    uint256 public constant IC10_X =
        5697191124914901219408901513601442561324208164645566497511242718204397743535;
    uint256 public constant IC10_Y =
        13398161619207397794324308592162009615115451562662451839052676578420491271203;
    uint256 public constant IC11_X =
        703123888741314718612309048386350636226232723398947337322732826265873810481;
    uint256 public constant IC11_Y =
        17990589954423602614263242460599822606354926012790592127594635530017447736000;
    uint256 public constant IC12_X =
        20393624977578917018885892283158705958560546595002668452425361396957472131164;
    uint256 public constant IC12_Y =
        19590758776110701291071416345258278715869484586955132519963026375488500561474;
    uint256 public constant IC13_X =
        12436544099918355712785605826913391779448933207323030677346777208134860342988;
    uint256 public constant IC13_Y =
        12934270829268999096893372612764637040591991408236553218822437244622467331607;
    uint256 public constant IC14_X =
        17956572623335638994475857660706169025078837539836899885807999861812007891829;
    uint256 public constant IC14_Y =
        15788541231435136223906443344147580532437154635912716511551645127845433777427;
    uint256 public constant IC15_X =
        17372427373514078940943510142559667491564581290960965924927622740257982261705;
    uint256 public constant IC15_Y =
        15857915612980925933684826813016864811106014452704060191542323376399865010576;
    uint256 public constant IC16_X =
        17706658396584983918235581578937131335399954610126317122698339854402062323466;
    uint256 public constant IC16_Y =
        19825721779656394025821381305312046990958274866881259324875151902399022916528;
    uint256 public constant IC17_X =
        20620988361254936794552318469605522229142851776281478715836384141520080141570;
    uint256 public constant IC17_Y =
        8859059503123755609281367511103088644004110641968218967910338769873511051761;
    uint256 public constant IC18_X =
        12631122413809660711555817700981016176438142813482101243197149713058144542227;
    uint256 public constant IC18_Y =
        2556186502760854102348974448979574846991952002272770169461095031136952271616;
    uint256 public constant IC19_X =
        17458248129570466726463169081527160609041285936662432661537029195640964876334;
    uint256 public constant IC19_Y =
        13311660137139351881541212173790929136853538186322689971135798269503166365287;
    uint256 public constant IC20_X =
        20376216183950978302528448687935566484992782628561612737636988612841263279656;
    uint256 public constant IC20_Y =
        20169118954698379344261930520187924042126994913369409717143332017835499608184;
    uint256 public constant IC21_X =
        13590288787452426901921148286585278258898382446775320387044914269174787786911;
    uint256 public constant IC21_Y =
        8747169299236194328036487885749156195653967424912382461452920152586239170329;
    uint256 public constant IC22_X =
        7674325401976365261930217729547312366599000999965896222120534931642700524203;
    uint256 public constant IC22_Y =
        19068217506565083003578053277160250956988289919655860507582338843332571021978;
    uint256 public constant IC23_X =
        19352748579310488859684030546811483397732185861890924210248349868791909751480;
    uint256 public constant IC23_Y =
        12154048074587184269542372566563175850267148361618941040848511983070399994545;
    uint256 public constant IC24_X =
        5781302722013869065299528236353742940267161069046098906267033438704274873397;
    uint256 public constant IC24_Y =
        17692093638206231489380310174596348635669977742969481065378179222721950073816;
    uint256 public constant IC25_X =
        1822112472095935411318382311555409139784633448197418086992049484249877317223;
    uint256 public constant IC25_Y =
        21492042244465545003762241091589873862989079378893002689743486138813696694800;
    uint256 public constant IC26_X =
        5603351942102452705019860367516099398860849474250143800383911460118571587263;
    uint256 public constant IC26_Y =
        3094600863124428771041895118538692524518496368868992103906097304480737853640;
    uint256 public constant IC27_X =
        7441415126376982767803363803637519563709295595343439983482489919240779377645;
    uint256 public constant IC27_Y =
        3076359757048038301182852617243931521181585988154293760812390384006896356182;
    uint256 public constant IC28_X =
        14900441524872817256320500300380092737890857259674155501716427566825132598416;
    uint256 public constant IC28_Y =
        12494120348218091892039246129978021993414195558596456765490457556412967109951;
    uint256 public constant IC29_X =
        5750365781992332384417028751570408231938568123690438954844611265235763415721;
    uint256 public constant IC29_Y =
        12272625903360264588429425090935995728552800950462484265649059624128745160550;
    uint256 public constant IC30_X =
        1862621976991045800447155762811695415777350522333110092968742495664769562796;
    uint256 public constant IC30_Y =
        18559201839005851072407866227831468715642200861728631518878477425805757269298;
    uint256 public constant IC31_X =
        1385302304779399923164390639587851358941432391526277932382765163789040623703;
    uint256 public constant IC31_Y =
        11968611566051487792573876012784928369981716184185714307126319967096287002644;
    uint256 public constant IC32_X =
        16587830688199775995326445992945741349754658301661942765538031557545371551275;
    uint256 public constant IC32_Y =
        19754146478491369725133569461490869112850762561747377519184934519660398688407;
    
    /// @dev memory pointer sizes
    uint16 public constant P_PUBLIC_SIGNALS_ACCUMULATOR_SIZE = 128;
    uint16 public constant P_TOTAL_SIZE = 896;

    function verifyProof(
        uint256[2] memory pointA_,
        uint256[2][2] memory pointB_,
        uint256[2] memory pointC_,
        uint256[32] memory publicSignals_
    ) public view returns (bool verified_) {
        assembly {
            function checkField(signal_) -> res_ {
                res_ := lt(signal_, SCALAR_FIELD_SIZE)
            }

            function g1MulAdd(pR_, x_, y_, s_) -> res_ {
                let pointer_ := mload(64) // free pointer

                mstore(pointer_, x_)
                mstore(add(pointer_, 32), y_)
                mstore(add(pointer_, 64), s_)

                res_ := staticcall(6000, 7, pointer_, 96, pointer_, 64) // ecMul
                res_ := and(res_, gt(returndatasize(), 0)) // check that multiplication succeeded

                if iszero(res_) {
                    leave
                }

                mstore(add(pointer_, 64), mload(pR_))
                mstore(add(pointer_, 96), mload(add(pR_, 32)))

                res_ := staticcall(150, 6, pointer_, 128, pR_, 64) // ecAdd
                res_ := and(res_, gt(returndatasize(), 0)) // check that addition succeeded
            }

            function checkPairing(pA_, pB_, pC_, pubSignals_, pointer_) -> res_ {
                let pPairing_ := add(pointer_, P_PUBLIC_SIGNALS_ACCUMULATOR_SIZE)

                mstore(pointer_, IC0_X)
                mstore(add(pointer_, 32), IC0_Y)

                /// @dev compute the linear combination of public signals
                if iszero(g1MulAdd(pointer_, IC1_X, IC1_Y, mload(add(pubSignals_, 0)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC2_X, IC2_Y, mload(add(pubSignals_, 32)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC3_X, IC3_Y, mload(add(pubSignals_, 64)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC4_X, IC4_Y, mload(add(pubSignals_, 96)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC5_X, IC5_Y, mload(add(pubSignals_, 128)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC6_X, IC6_Y, mload(add(pubSignals_, 160)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC7_X, IC7_Y, mload(add(pubSignals_, 192)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC8_X, IC8_Y, mload(add(pubSignals_, 224)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC9_X, IC9_Y, mload(add(pubSignals_, 256)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC10_X, IC10_Y, mload(add(pubSignals_, 288)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC11_X, IC11_Y, mload(add(pubSignals_, 320)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC12_X, IC12_Y, mload(add(pubSignals_, 352)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC13_X, IC13_Y, mload(add(pubSignals_, 384)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC14_X, IC14_Y, mload(add(pubSignals_, 416)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC15_X, IC15_Y, mload(add(pubSignals_, 448)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC16_X, IC16_Y, mload(add(pubSignals_, 480)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC17_X, IC17_Y, mload(add(pubSignals_, 512)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC18_X, IC18_Y, mload(add(pubSignals_, 544)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC19_X, IC19_Y, mload(add(pubSignals_, 576)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC20_X, IC20_Y, mload(add(pubSignals_, 608)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC21_X, IC21_Y, mload(add(pubSignals_, 640)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC22_X, IC22_Y, mload(add(pubSignals_, 672)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC23_X, IC23_Y, mload(add(pubSignals_, 704)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC24_X, IC24_Y, mload(add(pubSignals_, 736)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC25_X, IC25_Y, mload(add(pubSignals_, 768)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC26_X, IC26_Y, mload(add(pubSignals_, 800)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC27_X, IC27_Y, mload(add(pubSignals_, 832)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC28_X, IC28_Y, mload(add(pubSignals_, 864)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC29_X, IC29_Y, mload(add(pubSignals_, 896)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC30_X, IC30_Y, mload(add(pubSignals_, 928)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC31_X, IC31_Y, mload(add(pubSignals_, 960)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC32_X, IC32_Y, mload(add(pubSignals_, 992)))) {
                    leave
                }
                
                /// @dev -A
                mstore(pPairing_, mload(pA_))
                mstore(
                    add(pPairing_, 32),
                    mod(sub(BASE_FIELD_SIZE, mload(add(pA_, 32))), BASE_FIELD_SIZE)
                )

                /// @dev B
                mstore(add(pPairing_, 64), mload(mload(pB_)))
                mstore(add(pPairing_, 96), mload(add(mload(pB_), 32)))
                mstore(add(pPairing_, 128), mload(mload(add(pB_, 32))))
                mstore(add(pPairing_, 160), mload(add(mload(add(pB_, 32)), 32)))

                /// @dev alpha1
                mstore(add(pPairing_, 192), ALPHA_X)
                mstore(add(pPairing_, 224), ALPHA_Y)

                /// @dev beta2
                mstore(add(pPairing_, 256), BETA_X1)
                mstore(add(pPairing_, 288), BETA_X2)
                mstore(add(pPairing_, 320), BETA_Y1)
                mstore(add(pPairing_, 352), BETA_Y2)

                /// @dev public signals
                mstore(add(pPairing_, 384), mload(pointer_))
                mstore(add(pPairing_, 416), mload(add(pointer_, 32)))

                /// @dev gamma2
                mstore(add(pPairing_, 448), GAMMA_X1)
                mstore(add(pPairing_, 480), GAMMA_X2)
                mstore(add(pPairing_, 512), GAMMA_Y1)
                mstore(add(pPairing_, 544), GAMMA_Y2)

                /// @dev C
                mstore(add(pPairing_, 576), mload(pC_))
                mstore(add(pPairing_, 608), mload(add(pC_, 32)))

                /// @dev delta2
                mstore(add(pPairing_, 640), DELTA_X1)
                mstore(add(pPairing_, 672), DELTA_X2)
                mstore(add(pPairing_, 704), DELTA_Y1)
                mstore(add(pPairing_, 736), DELTA_Y2)

                res_ := staticcall(181000, 8, pPairing_, 768, pPairing_, 32) // ecPairing
                res_ := and(res_, mload(pPairing_)) // check that pairing succeeded
            }

            let pointer_ := mload(64) // free pointer
            mstore(64, add(pointer_, P_TOTAL_SIZE))

            /// @dev check that all public signals are in F
            verified_ := 1
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 0))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 32))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 64))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 96))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 128))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 160))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 192))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 224))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 256))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 288))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 320))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 352))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 384))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 416))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 448))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 480))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 512))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 544))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 576))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 608))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 640))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 672))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 704))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 736))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 768))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 800))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 832))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 864))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 896))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 928))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 960))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 992))))
            
            /// @dev check pairings
            if not(iszero(verified_)) {
                verified_ := checkPairing(pointA_, pointB_, pointC_, publicSignals_, pointer_)
            }
        }
    }
}
