// SPDX-License-Identifier: MIT

/* AUTOGENERATED FILE BY HARDHAT-ZKIT. DO NOT EDIT. */

pragma solidity >=0.7.0 <0.9.0;

contract WithdrawCircuitGroth16Verifier {
    // @dev scalar field size
    uint256 public constant SCALAR_FIELD_SIZE =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;
    /// @dev base field size
    uint256 public constant BASE_FIELD_SIZE =
        21888242871839275222246405745257275088696311157297823662689037894645226208583;

    /// @dev verification key data
    uint256 public constant ALPHA_X =
        20491192805390485299153009773594534940189261866228447918068658471970481763042;
    uint256 public constant ALPHA_Y =
        9383485363053290200918347156157836566562967994039712273449902621266178545958;
    uint256 public constant BETA_X1 =
        4252822878758300859123897981450591353533073413197771768651442665752259397132;
    uint256 public constant BETA_X2 =
        6375614351688725206403948262868962793625744043794305715222011528459656738731;
    uint256 public constant BETA_Y1 =
        21847035105528745403288232691147584728191162732299865338377159692350059136679;
    uint256 public constant BETA_Y2 =
        10505242626370262277552901082094356697409835680220590971873171140371331206856;
    uint256 public constant GAMMA_X1 =
        11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 public constant GAMMA_X2 =
        10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 public constant GAMMA_Y1 =
        4082367875863433681332203403145435568316851327593401208105741076214120093531;
    uint256 public constant GAMMA_Y2 =
        8495653923123431417604973247489272438418190587263600148770280649306958101930;
    uint256 public constant DELTA_X1 =
        18413979168680880508427857573499344678105139700199040952837451066239717429821;
    uint256 public constant DELTA_X2 =
        9898626626077518568379228412902424898657681523885533885565411617328460389922;
    uint256 public constant DELTA_Y1 =
        6007184160786324903714517413881807875499448146223314045078954717411897818016;
    uint256 public constant DELTA_Y2 =
        17841574180482311547923292068248229483419102900173905611468380600372583372822;

    uint256 public constant IC0_X =
        1989347808741798604476145984547616952751352055055300243388942465316163536890;
    uint256 public constant IC0_Y =
        18287141091950813472142285432947217857255288156969105476385431648941747790000;
    uint256 public constant IC1_X =
        21588062611189889344864608007646956350568930448852990739689758952508651394965;
    uint256 public constant IC1_Y =
        98867617019240069306705043616311394330926299234980402726491820133169484093;
    uint256 public constant IC2_X =
        15550575461234686720063491014368064382464483659875934656158426803714221382565;
    uint256 public constant IC2_Y =
        19120379509284667271969003793820599158352811626916363073794854942946766897866;
    uint256 public constant IC3_X =
        20223630843990402409968710763948629834919161710796588491358359466297300700679;
    uint256 public constant IC3_Y =
        2675223734590396478598414102060532012408669002722152868471093004240099725728;
    uint256 public constant IC4_X =
        9784390272502725404771544918680482012603159796207186791664900226814915108846;
    uint256 public constant IC4_Y =
        4889052086745915475149417214030367513059993224424723225882729911060823610425;
    uint256 public constant IC5_X =
        2802268021394373347198041589581099782960862283447005903992849422477600826465;
    uint256 public constant IC5_Y =
        10141289372445744520279703235726021593976465063055028344566354047067642069932;
    uint256 public constant IC6_X =
        17981075212502931682373066520328626140643179374293563468968969591565544442937;
    uint256 public constant IC6_Y =
        12322953543578476859639640121428089812676529591711769361698560759547148735859;
    uint256 public constant IC7_X =
        17529192146275002547478358208807882132911034198502579757089079197086721890541;
    uint256 public constant IC7_Y =
        4388812328349628025776515576481472717076265011573169880617467587465858259016;
    uint256 public constant IC8_X =
        13462596197467101747423899664117767499325135553613560455509720229714799487830;
    uint256 public constant IC8_Y =
        12083203262673030953642459095709136489775976186296926881097299438023841911749;
    uint256 public constant IC9_X =
        17019906054902305959332406672890853967066335368735806389106047492332171614235;
    uint256 public constant IC9_Y =
        11321377648794280332725602412481768552079979051137249946557057349865848834435;
    uint256 public constant IC10_X =
        12004837936896928828186069165842330195823900241045766933887963792976213731479;
    uint256 public constant IC10_Y =
        2795017854439755881864709191776142922107159587230115159310641655955551793825;
    uint256 public constant IC11_X =
        21721751483859419544076386106520492385804231583471287102329184574269367382127;
    uint256 public constant IC11_Y =
        1494799036427623303630306049192407908077332540741044828452816678230690958760;
    uint256 public constant IC12_X =
        2761434005088267474318136430578008369202159868741997526572692295542766967068;
    uint256 public constant IC12_Y =
        4036048972999556212132214896337493500664620928442864032564561739128205321674;
    uint256 public constant IC13_X =
        3489522740644890307435542545453392570336902680579166380511301988065761857470;
    uint256 public constant IC13_Y =
        20937161376515314963749249507373036130492475294409777928513175104326755904935;
    uint256 public constant IC14_X =
        15246253735871791668224050351529893541576242280197703313685085786454308195198;
    uint256 public constant IC14_Y =
        14542825447756802434365841254734849043796005892758280359295110591666008608130;
    uint256 public constant IC15_X =
        1875928679557964182259760561824797539257356137127515597882745846130733296261;
    uint256 public constant IC15_Y =
        15445101728156033566794154649854201878640042973936971994075877498715300589664;
    uint256 public constant IC16_X =
        7704361725176004808064710428275595097272350957161158742117148391001036974188;
    uint256 public constant IC16_Y =
        2616681396458669498399019027534121017878488418160952267486192744404696102688;
    
    /// @dev memory pointer sizes
    uint16 public constant P_PUBLIC_SIGNALS_ACCUMULATOR_SIZE = 128;
    uint16 public constant P_TOTAL_SIZE = 896;

    function verifyProof(
        uint256[2] memory pointA_,
        uint256[2][2] memory pointB_,
        uint256[2] memory pointC_,
        uint256[16] memory publicSignals_
    ) public view returns (bool verified_) {
        assembly {
            function checkField(signal_) -> res_ {
                res_ := lt(signal_, SCALAR_FIELD_SIZE)
            }

            function g1MulAdd(pR_, x_, y_, s_) -> res_ {
                let pointer_ := mload(64) // free pointer

                mstore(pointer_, x_)
                mstore(add(pointer_, 32), y_)
                mstore(add(pointer_, 64), s_)

                res_ := staticcall(6000, 7, pointer_, 96, pointer_, 64) // ecMul
                res_ := and(res_, gt(returndatasize(), 0)) // check that multiplication succeeded

                if iszero(res_) {
                    leave
                }

                mstore(add(pointer_, 64), mload(pR_))
                mstore(add(pointer_, 96), mload(add(pR_, 32)))

                res_ := staticcall(150, 6, pointer_, 128, pR_, 64) // ecAdd
                res_ := and(res_, gt(returndatasize(), 0)) // check that addition succeeded
            }

            function checkPairing(pA_, pB_, pC_, pubSignals_, pointer_) -> res_ {
                let pPairing_ := add(pointer_, P_PUBLIC_SIGNALS_ACCUMULATOR_SIZE)

                mstore(pointer_, IC0_X)
                mstore(add(pointer_, 32), IC0_Y)

                /// @dev compute the linear combination of public signals
                if iszero(g1MulAdd(pointer_, IC1_X, IC1_Y, mload(add(pubSignals_, 0)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC2_X, IC2_Y, mload(add(pubSignals_, 32)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC3_X, IC3_Y, mload(add(pubSignals_, 64)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC4_X, IC4_Y, mload(add(pubSignals_, 96)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC5_X, IC5_Y, mload(add(pubSignals_, 128)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC6_X, IC6_Y, mload(add(pubSignals_, 160)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC7_X, IC7_Y, mload(add(pubSignals_, 192)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC8_X, IC8_Y, mload(add(pubSignals_, 224)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC9_X, IC9_Y, mload(add(pubSignals_, 256)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC10_X, IC10_Y, mload(add(pubSignals_, 288)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC11_X, IC11_Y, mload(add(pubSignals_, 320)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC12_X, IC12_Y, mload(add(pubSignals_, 352)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC13_X, IC13_Y, mload(add(pubSignals_, 384)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC14_X, IC14_Y, mload(add(pubSignals_, 416)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC15_X, IC15_Y, mload(add(pubSignals_, 448)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC16_X, IC16_Y, mload(add(pubSignals_, 480)))) {
                    leave
                }
                
                /// @dev -A
                mstore(pPairing_, mload(pA_))
                mstore(
                    add(pPairing_, 32),
                    mod(sub(BASE_FIELD_SIZE, mload(add(pA_, 32))), BASE_FIELD_SIZE)
                )

                /// @dev B
                mstore(add(pPairing_, 64), mload(mload(pB_)))
                mstore(add(pPairing_, 96), mload(add(mload(pB_), 32)))
                mstore(add(pPairing_, 128), mload(mload(add(pB_, 32))))
                mstore(add(pPairing_, 160), mload(add(mload(add(pB_, 32)), 32)))

                /// @dev alpha1
                mstore(add(pPairing_, 192), ALPHA_X)
                mstore(add(pPairing_, 224), ALPHA_Y)

                /// @dev beta2
                mstore(add(pPairing_, 256), BETA_X1)
                mstore(add(pPairing_, 288), BETA_X2)
                mstore(add(pPairing_, 320), BETA_Y1)
                mstore(add(pPairing_, 352), BETA_Y2)

                /// @dev public signals
                mstore(add(pPairing_, 384), mload(pointer_))
                mstore(add(pPairing_, 416), mload(add(pointer_, 32)))

                /// @dev gamma2
                mstore(add(pPairing_, 448), GAMMA_X1)
                mstore(add(pPairing_, 480), GAMMA_X2)
                mstore(add(pPairing_, 512), GAMMA_Y1)
                mstore(add(pPairing_, 544), GAMMA_Y2)

                /// @dev C
                mstore(add(pPairing_, 576), mload(pC_))
                mstore(add(pPairing_, 608), mload(add(pC_, 32)))

                /// @dev delta2
                mstore(add(pPairing_, 640), DELTA_X1)
                mstore(add(pPairing_, 672), DELTA_X2)
                mstore(add(pPairing_, 704), DELTA_Y1)
                mstore(add(pPairing_, 736), DELTA_Y2)

                res_ := staticcall(181000, 8, pPairing_, 768, pPairing_, 32) // ecPairing
                res_ := and(res_, mload(pPairing_)) // check that pairing succeeded
            }

            let pointer_ := mload(64) // free pointer
            mstore(64, add(pointer_, P_TOTAL_SIZE))

            /// @dev check that all public signals are in F
            verified_ := 1
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 0))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 32))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 64))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 96))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 128))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 160))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 192))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 224))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 256))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 288))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 320))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 352))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 384))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 416))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 448))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 480))))
            
            /// @dev check pairings
            if not(iszero(verified_)) {
                verified_ := checkPairing(pointA_, pointB_, pointC_, publicSignals_, pointer_)
            }
        }
    }
}
